### ISSUE TITLE
Can we install this pm confluent platform. it also has kafka-connect to sink/source from the salesforce streaming API.

### ISSUE THREAD

**Issue by Gk8143197049** [nodefluent/salesforce-kafka-connect#12]
Can we install this pm confluent platform. it also has kafka-connect to sink/source from the salesforce streaming API.

**Comment by GirishPinumalla** [comment]
Can we install this package on  confluent platform. it also has kafka-connect to sink/source from the salesforce streaming API. How to integrate?

**Comment by Gk8143197049** [comment]
@holgeradam Can you please help with this issue.? whenever you have time.if it works and I can build documents on the saleaforce integrate and contribute back to nodefluent( I understand this is not related to confluent at all) 

Thanks.

**Comment by Gk8143197049** [comment]
Got you !! 

Thanks . I really appreciate your tine and effort.
